services:
    gemini-imagen:
        build: .
        network_mode: host
        volumes:
            - ./tmp:/app/tmp
            - ./user-data:/app/user-data
        environment:
            - NODE_ENV=production
            - PORT=${PORT}
        restart: unless-stopped
